### ISSUE TITLE
Error: threshold should be positive

### ISSUE THREAD

**Issue by Close-your-eyes** [LTLA/kmknn#24]
Dear Aaron,

I received an error from a function of this package: https://github.com/plger/scDblFinder, namely computeDoubletDensity.

Internally, it passes a bunch of arguments to BiocNeighbors::queryNeighbors and the error being returned is this:

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error: threshold should be positive

I uploaded all arguments as RDS files in an archive which can be found here:
https://www.dropbox.com/scl/fi/xiv6cyjp341jhf0lx4y3c/Archive.zip?rlkey=pvszf1bzjdthsslozgpqggqxl&dl=0

This command reproduces the error:
```
BiocNeighbors::queryNeighbors(X = readRDS("sim.pcs.rds"),
                              query = readRDS("pcs.rds"),
                              threshold = readRDS("self.dist.rds") * 1.00000001, # bump it up to avoid issues with numerical precision during tests.
                              BNPARAM = readRDS("BNPARAM.rds"),
                              BPPARAM = readRDS("BPPARAM.rds"),
                              get.distance=FALSE,
                              get.index=FALSE)
```

Can you tell what causes the error?

Thanks a lot. Chris.

**Comment by LTLA** [comment]
The immediate cause is pretty clear - `threshold` should be positive, but your `self.dist.rds` has a few zeros, hence the error about `threshold` not being positive. I suppose I could weaken that requirement to just require non-negative thresholds, which would avoid this error.

The root cause is that the affected cells have a distance of 0 to the `k`-th nearest neighbor. In `computeDoubletDensity()`, the default `k` is 50, so that implies that you have a few cells that have been duplicated 50 times. I suspect that these are low-quality cells (e.g., all-zero libraries) as it is difficult to believe that you could get exactly identical profiles for two real cells, let alone 50.

In any case, even if I loosen the requirements here, you're likely to get odd results from the affected cells in `computeDoubletDensity()`. If you accept that duplicate cells are unlikely, then it's even more unlikely to construct simulated doublets with a distance of zero to those cells; so all of those affected cells will probably get a doublet score of zero, regardless of what they actually are.

**Comment by LTLA** [comment]
After some further investigation, I remember why I set that positive requirement. Due to numerical precision issues, setting `threshold=0` isn't actually guaranteed to find the duplicate points.

```r
set.seed(1004)
nobs <- 1000
ndim <- 10
X <- matrix(runif(nobs * ndim), nrow=nobs)

# Searching at a very low positive threshold, so each point should
# basically only return itself as the neighbor within threshold.
dupes <- rangeQueryKmknn(X, X, threshold=1e-20)

# So we should expect that there is exactly one neighbor in each
# point's set of neighbors... but over 10% have no neighbors at all.
mean(lengths(dupes$index) == 0)
## [1] 0.108
```

This effect is caused by some transformations within the KNN algorithms that can modify a zero distance to a slightly non-zero distance. To be clear, this is not a bug, as the calculations are arithmetically correct but practically approximate given the nature of floating-point calculations on real CPUs. (Indeed, YMMV on the test above, depending on your CPU architecture.) Numerical imprecision usually isn't a major issue but if you're doing something as stringent as an exact comparison to zero, it makes a difference. I didn't want to deal with all of these problems so I just forbade zero thresholds.

As I said above, this situation is already pretty weird, given that you seem to have duplicate cells floating around.  A simple fix would be for `computeDoubletDensity()` to set a minimum value on the threshold, maybe something like `.Machine$double.xmin`, just to get the thing to run. The results might not be sensible for the affected cells but they probably won't be sensible anyway and at least you'd get some doublet scores back for the other cells. Pinging @plger for  his thoughts.

**Comment by plger** [comment]
The alternative would be to trigger an informative error on the ground that there's something wrong with some of the cells, and that some kind of filtering seems required. At any rate, even if you do simply add double.xmin to avoid the error, it seems desirable to give the user a warning that something is weird.
Right now `computeDoubletDensity` doesn't do any check on library size (beyond >0 through the size.factors), perhaps that could be added if we think that extremely low read count is the main cause of the identical cells. Alternatively, since explicitly checking for identical cells is expensive, we could have a check on the `threshold` argument, run it nonetheless with +double.xmin, but give a warning if there are many zeros?
Either way @LTLA let me know if you want me to take action on this.

**Comment by Close-your-eyes** [comment]
Thanks for your detailed answers. In order to process the data set that I am currently facing, I will try to remove low quality cells which probably happen to have very few UMIs. Needless to say, Informative error messages or additional checks on user input are a plus. However, I know, one cannot foresee every problem before it occurs. Thanks you.

**Comment by Close-your-eyes** [comment]
So, I think you are right. First of all, this issue came up with the raw (no filtered) UMI matrices as returned from CellRanger. Accordingly, the matrix contains empty or almost empty droplets. When I filtered for cells which have at least 5 UMI (so rowSums >= 5) for the subset.row features as passed to scDblFinder::computeDoubletDensity, they error does not occur. Likely because with 5 UMI minimum there are no identical (duplicate) cells which have these UMIs at the very same features. However, I am now doing this filtering outside of the computeDoubletDensity function but it seems a generic thing that could be checked within the function. Considering users with less experience it may be worth it to trigger an informative error ?!
All in all though, thanks for your support.

**Comment by LTLA** [comment]
Yes, a more informative error would be a good idea; probably better than trying to plaster over the problem by setting a minimum distance. As @plger mentione, we already have a nice error message for the size factor case:
 
https://github.com/plger/scDblFinder/blob/59c6682307d7a986f6300547b88a9f501b2c820e/R/computeDoubletDensity.R#L125-L128

So it doesn't seem to be too much of a stretch to add something like:

```r
if (any(self.dist == 0)) {
     stop("Duplicate cells detected. These are probably low-quality cells that have very few reads, and should be filtered out.")
}
```

after:

https://github.com/plger/scDblFinder/blob/59c6682307d7a986f6300547b88a9f501b2c820e/R/computeDoubletDensity.R#L145

Which should be good enough for now. I'm not sure it's worth trying to salvage something from non-QC-filtered input, given that the simulation process is probably already screwed if you start adding cells to, e.g., empty droplets to form "doublets".

@plger what do you think?

**Comment by plger** [comment]
Agreed...
I've just added the error msg:
https://github.com/plger/scDblFinder/commit/99b947a49a4f3f3bd1a2203fe2296a6dc143fe11
Will push to Bioc once the checks have passed.
Cheers
