### ISSUE TITLE
Provide Algorithm Suggestions in Vignette

### ISSUE THREAD

**Issue by DarioS** [LTLA/kmknn#4]
It would be nice if the vignette discussed a range of different scenarios with different sample and feature sizes and recommended which algorithm to use in each case. Perhaps some graphs of timings would also be of interest to the reader.

**Comment by LTLA** [comment]
I would be reluctant to put timing graphs in the vignette. I would prefer to reference them from somewhere else; the [OkNN2018](https://github.com/LTLA/OkNN2018) repository might be a more natural home for them, e.g., on a `gh-pages` branch.

For a long time, the only choice was between Annoy and KMKNN, and there the trade-off was pretty clear. Annoy is approximate and thus much faster, but - well, it's approximate. Sometimes the approximation is okay, other times it's not. But I reckon most users will not be able to determine whether their data contains parallel hyperplanes or other high-dimensional structures that compromise accuracy. So in this respect, the only practical advice is to "use approximate methods when exact methods are too slow for you".

I've recently added VP trees as another method for exact searches. It is possible that we could provide some general advice about whether to use KMKNN or VP trees by default. My guess is that VP trees would be faster in most circumstances because it blocks off parts of the search space more efficiently, but KMKNN might be faster at high dimensions where most points have to be searched anyway and the simpler index structure reduces the overhead (based on similar comparisons with KD trees). However, this is really YMMV-able advice that depends on the underlying structure, and it may be the case that no general recommendation exists.

Feel free to make PRs to OkNN2018 to test the new search methods (just modify `functions.R`) and stick the timing results somewhere. Not on `master`, though, I like to keep that code-only.

**Comment by LTLA** [comment]
Some very brief testing with the first 50 PCs of the 68K PBMC data set suggests that KMKNN is quite a bit faster at getting the first 15 neighbors -  175 seconds vs 300 seconds for VP trees. Of course, Annoy blows both of them away: 20 seconds, which is pretty impressive.

The timings flip around in low-dimensional space, though; for 5 PCs, VP trees take 1.7 seconds, KMKNN takes 5 seconds and - funnily enough - Annoy still takes 20 seconds! I'm not sure about why Annoy takes so long, probably overheads related to memory mapped files.

So, all in all, I guess I wasn't too far off with my initial expectations. You'll need to test a lot more datasets though before you can consider these to be generalizable observations.

**Comment by DarioS** [comment]
Thanks for creating these benchmarks. I'll be mindful of them when choosing a method.
